// @vitest-environment jsdom
import React from 'react';
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { within } from '@testing-library/react';
import { longPress } from '../support/touchEvents';
import { copySharedImage, downloadSharedImage } from '../../services/imageSharing';
vi.mock('../../services/imageSharing', async original => ({ ...await original<typeof import('../../services/imageSharing')>(), copySharedImage: vi.fn(async () => {}), downloadSharedImage: vi.fn(async () => {}) }));
import { PixivGallery } from '../../components/PixivGallery';
import { pixivService, importPixivImageAsFile, type PixivIllust } from '../../services/pixivService';
import { db } from '../../services/dbService';
import { api } from '../../services/api';
import { galleryHistoryService } from '../../services/galleryHistoryService';
import type { User } from '../../types';
vi.mock('../../services/pixivService', async original => ({ ...await original<typeof import('../../services/pixivService')>(), pixivService: { status: vi.fn(), feed: vi.fn(), startPixivLogin: vi.fn(), getPixivLoginStatus: vi.fn(), addBookmark: vi.fn(), deleteBookmark: vi.fn(), getRelated: vi.fn(async () => ({ items: [] })) }, importPixivImageAsFile: vi.fn() }));
vi.mock('../../services/dbService', () => ({ db: { getInspirationsBySource: vi.fn(), updateInspiration: vi.fn() } }));
vi.mock('../../services/api', () => ({ api: { uploadFile: vi.fn(), post: vi.fn() } }));
vi.mock('../../services/galleryHistoryService', () => ({ galleryHistoryService: { recordView: vi.fn(), getHistory: vi.fn(() => []) } }));
vi.mock('../../components/ShortestColumnMasonry', () => ({ useMasonryColumnCount: () => 3, ShortestColumnMasonry: ({ items, renderItem }: { items: PixivIllust[]; renderItem: (item: PixivIllust) => React.ReactNode }) => <div>{items.map(renderItem)}</div> }));
const illust: PixivIllust = { id: '100', title: 'synthetic artwork', type: 'illust', caption: '', restrict: 0, xRestrict: 0, tags: ['原站标签'], pageCount: 2, width: 800, height: 1200, totalBookmarks: 10, totalViews: 20, createDate: '', user: { id: '10', name: 'artist', account: '' }, urls: { thumb: '', medium: '', large: '', original: 'https://i.pximg.net/p0.png' }, metaPages: ['https://i.pximg.net/p0.png', 'https://i.pximg.net/p1.png'] };
beforeEach(() => {
  vi.clearAllMocks(); localStorage.clear(); sessionStorage.clear();
  vi.stubGlobal('fetch', vi.fn(async () => new Response('{}')));
  vi.stubGlobal('matchMedia', vi.fn(() => ({ matches: false, addEventListener() {}, removeEventListener() {} })));
  vi.stubGlobal('IntersectionObserver', class { observe() {} disconnect() {} });
  vi.mocked(pixivService.status).mockResolvedValue({ connected: true });
  vi.mocked(pixivService.feed).mockImplementation(async mode => ({ mode, items: mode === 'related' ? [] : [illust], nextCursor: null, nextUrl: null, fetchedAt: Date.now() }));
  vi.mocked(db.getInspirationsBySource).mockResolvedValue([]);
  vi.mocked(galleryHistoryService.getHistory).mockReturnValue([]);
  vi.mocked(importPixivImageAsFile).mockResolvedValue(new File(['synthetic'], 'image.png', { type: 'image/png' }));
  vi.mocked(api.uploadFile).mockResolvedValue({ url: '/api/assets/uploaded' });
  vi.mocked(api.post).mockImplementation(async (_path, body) => ({ item: body }));
});
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
it.each([false, true])('自动回调=%s：登录提示显示真实后台阶段，不覆盖为继续账号教程', async automaticCallback => {
  vi.mocked(pixivService.status).mockResolvedValue({ connected: false });
  const session = { id: 'test-login-session', state: 'exchanging' as const, automaticCallback, expiresAt: Date.now() + 300000, message: '正在完成连接…' };
  vi.mocked(pixivService.startPixivLogin).mockResolvedValue(session);
  vi.mocked(pixivService.getPixivLoginStatus).mockResolvedValue(session);
  render(<PixivGallery active currentUser={{ id: 'owner' } as User} notify={vi.fn()} onNavigateToPlayground={vi.fn()} />);
  fireEvent.click(await screen.findByRole('button', { name: '在默认浏览器登录' }));
  expect(await screen.findByText('正在完成连接…')).toBeTruthy();
  expect(screen.queryByText(/继续使用此账号/)).toBeNull();
  expect(Boolean(screen.queryByRole('textbox', { name: 'Pixiv 登录完成地址' }))).toBe(!automaticCallback);
});
it.each([false, true])('足迹=%s：卡片取首图且不打开详情，详情分享跟随当前页', async history => {
  vi.mocked(galleryHistoryService.getHistory).mockReturnValue([{ id: 'pixiv:100', source: 'pixiv', sourceId: '100', title: illust.title, artistName: illust.user.name, previewUrl: '', sampleUrl: illust.metaPages[0], tags: [], viewedAt: 1 }]);
  const { container } = render(<PixivGallery active currentUser={{ id: 'owner' } as User} notify={vi.fn()} onNavigateToPlayground={vi.fn()} />);
  const open = await screen.findByRole('button', { name: /synthetic artwork.*artist/ });
  if (history) fireEvent.click(screen.getAllByRole('button', { name: '足迹' })[0]);
  const card = screen.getByRole('button', { name: /synthetic artwork.*artist/ }).closest('article')!;
  fireEvent.click(within(card).getByRole('button', { name: '复制图片' }));
  await waitFor(() => expect(copySharedImage).toHaveBeenLastCalledWith('/api/media?source=' + encodeURIComponent(illust.metaPages[0]) + '&variant=original', false));
  expect(galleryHistoryService.recordView).not.toHaveBeenCalled();
  fireEvent.click(history ? within(card).getByRole('button', { name: /synthetic artwork.*artist/ }) : open);
  const firstSurface = container.querySelector('img[alt="synthetic artwork 第 1 页"]')!.closest('.press-reveal-surface')!;
  longPress(firstSurface);
  expect(firstSurface.getAttribute('data-press-revealed')).toBe('true');
  fireEvent.click(screen.getByRole('button', { name: '下一页' }));
  const surface = container.querySelector('img[alt="synthetic artwork 第 2 页"]')!.closest('.press-reveal-surface')!;
  expect(surface).toBe(firstSurface);
  expect(surface.hasAttribute('data-press-revealed')).toBe(false);
  fireEvent.click(within(surface as HTMLElement).getByRole('button', { name: '下载图片' }));
  await waitFor(() => expect(downloadSharedImage).toHaveBeenLastCalledWith('/api/media?source=' + encodeURIComponent(illust.metaPages[1]) + '&variant=original', 'pixiv-100-p2.png', false));
});
it('相关推荐沿用首图取用，复制图片不切换当前详情', async () => {
  const related = { ...illust, id: '102', title: 'related synthetic', metaPages: ['https://i.pximg.net/related.png'] };
  vi.mocked(pixivService.getRelated).mockResolvedValueOnce([related]);
  render(<PixivGallery active currentUser={{ id: 'owner' } as User} notify={vi.fn()} onNavigateToPlayground={vi.fn()} />);
  fireEvent.click(await screen.findByRole('button', { name: /synthetic artwork.*artist/ }));
  const open = await screen.findByRole('button', { name: '查看相关作品 related synthetic' });
  const card = open.closest('.press-reveal-surface')!;
  fireEvent.click(within(card as HTMLElement).getByRole('button', { name: '复制图片' }));
  await waitFor(() => expect(copySharedImage).toHaveBeenLastCalledWith('/api/media?source=' + encodeURIComponent(related.metaPages[0]) + '&variant=original', false));
  expect(screen.getByRole('link', { name: '查看原帖' }).getAttribute('href')).toBe('https://www.pixiv.net/artworks/100');
});
it.each(['masonry', 'portrait', 'square', 'history'])('Pixiv %s 卡片沿用 AITag 暗度，切换和关闭详情同步恢复', async layout => {
  const works = [illust, { ...illust, id: '101', title: 'second artwork' }];
  localStorage.setItem('nai_mobile_image_display', JSON.stringify({ layout }));
  vi.mocked(pixivService.feed).mockImplementation(async mode => ({ mode, items: works, nextCursor: null, nextUrl: null, fetchedAt: Date.now() }));
  vi.mocked(galleryHistoryService.getHistory).mockReturnValue(works.map(work => ({
    id: `pixiv:${work.id}`, source: 'pixiv', sourceId: work.id, title: work.title,
    artistName: work.user.name, previewUrl: '', sampleUrl: '', tags: [], viewedAt: 1,
  })));
  render(<PixivGallery active currentUser={{ id: 'owner' } as User} notify={vi.fn()} onNavigateToPlayground={vi.fn()} />);
  await screen.findByRole('button', { name: /synthetic artwork.*artist/ });
  if (layout === 'history') fireEvent.click(screen.getAllByRole('button', { name: '足迹' })[0]);
  const first = screen.getByRole('button', { name: /synthetic artwork.*artist/ });
  const second = screen.getByRole('button', { name: /second artwork.*artist/ });
  const cards = [first.closest('article')!, second.closest('article')!];
  cards.forEach(card => expect(card.className).not.toContain('brightness-'));
  fireEvent.click(first);
  expect(cards[0].className).toContain('ring-2');
  expect(cards[0].className).not.toContain('brightness-');
  expect(cards[1].className).toContain('brightness-[.7]');
  fireEvent.click(second);
  expect(cards[0].className).toContain('brightness-[.7]');
  expect(cards[1].className).not.toContain('brightness-');
  fireEvent.click(screen.getByRole('button', { name: '关闭' }));
  cards.forEach(card => expect(card.className).not.toContain('brightness-'));
});

it('Pixiv 当前页保存原图与原站标签，不把原站标签假装成生图提示词，主操作直接反推', async () => {
  render(<PixivGallery active currentUser={{ id: 'owner', username: 'test' } as User} notify={vi.fn()} onNavigateToPlayground={vi.fn()} />);
  fireEvent.click(await screen.findByRole('button', { name: /synthetic artwork.*artist/ }));
  await waitFor(() => expect(screen.getByRole('button', { name: '图片反推' }).hasAttribute('disabled')).toBe(false));
  expect(screen.queryByRole('button', { name: '导入实验室' })).toBeNull();
  expect(screen.queryByRole('button', { name: '更多' })).toBeNull();
  const source = screen.getByRole('link', { name: '查看原帖' });
  expect(source.closest('header')).toBeTruthy();
  expect(source.getAttribute('href')).toBe('https://www.pixiv.net/artworks/100');
  expect(screen.getByRole('group', { name: '图片操作' }).contains(source)).toBe(false);
  fireEvent.click(screen.getByRole('button', { name: '下一页' }));
  await waitFor(() => expect(screen.getByRole('button', { name: '加入灵感库' }).hasAttribute('disabled')).toBe(false));
  fireEvent.click(screen.getByRole('button', { name: '加入灵感库' }));
  await waitFor(() => expect(api.post).toHaveBeenCalledWith('/inspirations', expect.objectContaining({ prompt: '', imageUrl: '/api/assets/uploaded', title: 'synthetic artwork · 第 2 页', analysis: { externalSourceTags: ['原站标签'], externalSourcePage: 1 }, sourceId: '100' })));
  expect(importPixivImageAsFile).toHaveBeenCalledWith('https://i.pximg.net/p1.png');
});

it('作者名直接进入全集，站内心形收藏与本地灵感保存区分，执行中阻止重复并保持状态', async () => {
  const notify = vi.fn();
  render(<PixivGallery active currentUser={{ id: 'owner', username: 'test' } as User} notify={notify} onNavigateToPlayground={vi.fn()} />);
  fireEvent.click(await screen.findByRole('button', { name: /synthetic artwork.*artist/ }));
  await waitFor(() => expect(screen.getByRole('button', { name: '加入灵感库' }).hasAttribute('disabled')).toBe(false));
  expect(screen.queryByRole('button', { name: '作者全集' })).toBeNull();
  fireEvent.click(screen.getByRole('button', { name: '查看 artist 的作者全集' }));
  await waitFor(() => expect(pixivService.feed).toHaveBeenLastCalledWith('user', expect.objectContaining({ params: { user_id: '10' } })));
  let finish!: () => void;
  vi.mocked(pixivService.addBookmark).mockReturnValueOnce(new Promise(resolve => { finish = () => resolve({ success: true }); }));
  const favorite = screen.getByRole('button', { name: '收藏到 Pixiv' });
  expect(favorite.getAttribute('aria-pressed')).toBe('false');
  expect(screen.getByRole('group', { name: '图片操作' }).contains(favorite)).toBe(true);
  expect(favorite.classList.contains('w-10')).toBe(true);
  fireEvent.click(favorite);
  const pending = screen.getByRole('button', { name: '正在同步 Pixiv 收藏' });
  expect(pending.hasAttribute('disabled')).toBe(true);
  fireEvent.click(pending); expect(pixivService.addBookmark).toHaveBeenCalledTimes(1);
  await act(async () => finish());
  const active = screen.getByRole('button', { name: '取消 Pixiv 收藏' });
  expect(active.getAttribute('aria-pressed')).toBe('true');
  expect(active.querySelector('svg')?.classList.contains('fill-current')).toBe(true);
  fireEvent.click(active);
  await waitFor(() => expect(pixivService.deleteBookmark).toHaveBeenCalledWith('100'));
  await screen.findByRole('button', { name: '收藏到 Pixiv' });
  expect(api.post).not.toHaveBeenCalled(); expect(importPixivImageAsFile).not.toHaveBeenCalled();
  vi.mocked(pixivService.addBookmark).mockRejectedValueOnce(new Error('synthetic failure'));
  fireEvent.click(screen.getByRole('button', { name: '收藏到 Pixiv' }));
  await waitFor(() => expect(notify).toHaveBeenCalledWith('synthetic failure', 'error'));
  expect(screen.getByRole('button', { name: '收藏到 Pixiv' }).getAttribute('aria-pressed')).toBe('false');
});
