export default {
  appId: 'com.naiatelier.desktop',
  productName: 'NAI Atelier',
  directories: { app: '.desktop-build/app', output: 'release', buildResources: 'desktop' },
  files: ['desktop/**/*', 'scripts/desktop-runtime.mjs', 'package.json', '!node_modules{,/**/*}'],
  // extraResources 的根 node_modules 会被打包器默认跳过，需要独立映射。
  extraResources: [
    { from: '.desktop-build/runtime', to: 'runtime', filter: ['**/*'] },
    { from: '.desktop-build/runtime/node_modules', to: 'runtime/node_modules', filter: ['**/*'] },
    { from: 'desktop/install-prerequisites.ps1', to: 'install-prerequisites.ps1' },
    { from: 'desktop/uninstall-integration.ps1', to: 'uninstall-integration.ps1' },
  ],
  asar: true,
  npmRebuild: false,
  publish: null,
  electronVersion: '44.5.1',
  win: {
    target: [{ target: 'nsis', arch: ['x64'] }],
    icon: 'public/nai-atelier.ico',
    artifactName: 'NAI-Atelier-Setup-${version}-${arch}.${ext}',
  },
  nsis: {
    useZip: true,
    differentialPackage: false,
    oneClick: false,
    perMachine: false,
    allowElevation: true,
    allowToChangeInstallationDirectory: true,
    createDesktopShortcut: true,
    createStartMenuShortcut: true,
    shortcutName: 'NAI Atelier',
    uninstallDisplayName: 'NAI Atelier',
    deleteAppDataOnUninstall: false,
    runAfterFinish: true,
    installerLanguages: ['zh_CN', 'en_US'],
    language: '2052',
    license: 'LICENSE',
    include: 'desktop/installer.nsh',
  },
};
